name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run fmt
        run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo clippy --verbose --all --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose  --all --all-targets --all-features
